envs:
- key: DEBUG
  scope: RUN_AND_BUILD_TIME
  value: "True"
- key: DISABLE_COLLECTSTATIC
  scope: RUN_AND_BUILD_TIME
  value: "1"
- key: DATABASE_URL
  scope: RUN_TIME
  value: ${superherodb.DATABASE_URL}
- key: POSTGRES_DB
  scope: RUN_AND_BUILD_TIME
  value: ${superherodb.DATABASE}
- key: POSTGRES_HOST
  scope: RUN_AND_BUILD_TIME
  value: ${superherodb.HOSTNAME}
- key: POSTGRES_USER
  scope: RUN_AND_BUILD_TIME
  value: ${superherodb.USERNAME}
- key: POSTGRES_PASSWORD
  scope: RUN_AND_BUILD_TIME
  value: ${superherodb.PASSWORD}
- key: POSTGRES_PORT
  scope: RUN_AND_BUILD_TIME
  value: ${superherodb.PORT}
name: urchin
region: nyc
services:
- environment_slug: python
  github:
    branch: main
    deploy_on_push: true
    repo: Luna0500/PythonWebApps
  http_port: 8080
  instance_count: 1
  instance_size_slug: basic-xxs
  name: urchin-app
  routes:
  - path: /
  run_command: |
    python manage.py migrate --no-input
    gunicorn --worker-tmp-dir /dev/shm config.wsgi
  source_dir: Student/08/SuperGallery
static_sites:
- environment_slug: html
  github:
    branch: main
    deploy_on_push: true
    repo: Luna0500/PythonWebApps
  name: urchin-app-static
  routes:
  - path: /static
  source_dir: Student/08/SuperGallery/static